# Generated by Django 4.1.7 on 2023-02-21 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(null=True, upload_to='ok')),
                ('name', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('about', models.TextField()),
            ],
        ),
    ]
